apiVersion: apps/v1
kind: Deployment
metadata:
  name: dotnetworld
spec:
  selector:
    matchLabels:
      app: dotnetworld
  replicas: 1 
  template: 
    metadata:
      labels:
        app: dotnetworld
    spec:
      containers:
      - name: dotnetworld
        image: karthequian/dotnetexample:latest
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
 name: dotnetworld
spec:
 type: NodePort
 selector:
   app: dotnetworld
 ports:
   - name: client
     protocol: TCP
     port: 80
     nodePort: 32080
 selector:
   app: dotnetworld